config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  resources :posts, except: [:destroy] do
    resources :comments, only: [:create]
  end
  
  resources :categories, only: [:create, :show, :new]
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence: true, uniqueness: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post

  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true
  validates :description, presence: true
  validates :url, presence: true, uniqueness: true
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :category
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params.require(:category).permit(:name))
    if @category.save
      flash[:notice] = "Category Created"
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(params.require(:comment).permit(:body))    
    @comment.creator = User.first
    if @comment.save
      flash[:notice] = "Comment Created"
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update]

  def index
    @posts = Post.all
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = User.first

    if @post.save
      flash[:notice] = "Your post was created."
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def edit; end

  def update   
    if @post.update(post_params)
      flash[:notice] = 'Post was updated'
      redirect_to posts_path(@post)
    else
      render 'edit'
    end
  end

  def set_post
    @post = Post.find(params[:id])
  end

  private

  def post_params
    params.require(:post).permit(:title, :description, :url, category_ids: [])

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def fix_url(url)
    url.start_with?("http://") ? url : "http://#{url}"
  end

  def fix_datetime(dt)
    dt.strftime("%D %R") 
  end
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %></span>

app/views/categories/new.html.erb
<%= render 'shared/title', title: 'Create a Category' %>

<%= render 'shared/errors', obj: @category %>

<div class="well">
  <%= form_for @category do |f| %>
    <div class="control-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <%= f.submit("Create New Category", class: "btn btn-success") %>
  <% end %>
</div>

app/views/categories/show.html.erb
<% all_posts = link_to('All Posts', posts_path) %>

<%= render 'shared/title', title: "#{all_posts} &raquo; #{@category.name}".html_safe %>

<% @category.posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
  <li>
    <%= link_to 'link', '' %>
  </li> 
</ul>
<div class="btn-group nav_item">
  <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
    Categories <span class="caret"></span>
  <% end %>
  <ul class="dropdown-menu">
    <% Category.all.each do |category| %>
      <li>
        <%= link_to category.name, category_path(category) %>
      </li>
    <% end %>
    <li class="divider"></li>
    <li>
      <%= link_to(new_category_path) do %>
        <i class="icon-heart"></i>
        New Category
      <% end %> 
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= render "shared/errors", obj: @post %>

<div class="well">
  <%= form_for @post do |f| %>
    <div class="control-group">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="control-group">
      <%= f.label :url %>
      <%= f.text_field :url %>
    </div>
    <div class="control-group">
      <%= f.label :description %>
      <%= f.text_area :description, rows: 6 %>
    </div>
    <div class='control-group'>
      <%= f.label "Categories" %>
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
        <% cb.label(class: 'checkbox inline') {cb.check_box(class: 'checkbox') + cb.text} %>
      <% end %>
    </div>
    <%= f.submit(@post.new_record? ? "Create Post" : "Update Post", class: "btn btn-primary") %>
  <% end %>
 </div>

app/views/posts/_post.html.erb
  <div class="row">
    <div class="span8 well">
      <%= render post.categories %>
      <h4><%= link_to post.title, fix_url(post.url) %></h4>
      <p><%= post.description %></p>
      <p>
        <span class="quiet">Created by </span> <%= post.creator.username %> <small>at</small> <%= fix_datetime(post.created_at) %> 
      </p>
      <small>
        <spam>
          <%= link_to("#{post.comments.size} comments", post_path(post)) %>
        </span>
      </small>
    </div>
  </div>

app/views/posts/edit.html.erb
<%= render "shared/title", title: "Edit this post." %>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= render "shared/title", title: "All Posts" %>

<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

app/views/posts/new.html.erb
<%= render "shared/title", title: "Create a new post" %>

<%= render 'form' %>

app/views/posts/show.html.erb
<p class="pull-right">
  [<%= link_to "Edit this post", edit_post_path(@post) %>]
</p>

<p>
  <%= render @post.categories %>
</p>

<%= render "shared/title", title: @post.title %>

<p>
  <%= @post.description %>
</p>
<hr/>

<%= render "shared/errors", obj: @comment %>

<div class="well">
  <%= form_for [@post, @comment] do |f| %>
    <div class="control-group">
      <%= f.label :body, "Leave a comment" %>
      <%= f.text_area :body, rows: 5, class: "span4"  %>
    </div>
    <%= f.submit "Submit Comment", class: 'btn btn-primary' %>
  <% end %>
</div>

<p>Comments:</p>
<% @post.comments.each do |comment| %>
  <div class="well span8">
    <em>"<%= comment.body %>"</em>
    <span class="quiet">Created by </span> <%= comment.creator.username %> <small>at</small> <%= comment.created_at %> 
  </div>
<% end %>

app/views/shared/_errors.html.erb
<%if obj.errors.any? %>
  <div class="row">
    <div class="alert alert-error span8">
      <h5>Fix the following errors</h5>
      <% obj.errors.full_messages.each do |msg| %>
        <ul>
          <li> <%= msg %> </li>
        </ul>
      <% end %>
    </div>
  </div> 
<% end %>

app/views/shared/_title.html.erb
<p class="lead"> 
  <%= title %>
  <hr/>
</p>